Upgrade scrypt-ts to v0.1.5-beta.4
sCrypt-Inc/scryptTS-examples pull request #10
Opened 2023-01-07 14:20 UTC by gitzhou

2023-01-07 14:23 UTC, gitzhou commented
Fix #9

2023-01-07 17:41 UTC, xhliu requested changes
Almost there.

2023-01-07 17:41 UTC, xhliu commented on src/contracts/acs.ts
> +        assert(this.checkPreimageSigHashType(txPreimage, SigHash.ANYONECANPAY_SINGLE), 'preimage check failed');
Use this syntax and remove `checkPreimage*` everywhere.
https://github.com/sCrypt-Inc/scrypt-ts/blob/4c45b5ded1a8ae625e8d57ebad6211bc570b0d4c/test/contracts/acs.ts#L17

2023-01-07 17:41 UTC, xhliu commented on src/contracts/advancedCounter.ts
> +        assert(this.updateStateSigHashType(txPreimage, amount, SigHash.ANYONECANPAY_SINGLE), 'stateSigHashType update failed');
Same here.

2023-01-09 08:04 UTC, zhfnjust commented on src/contracts/ackermann.ts
> +    static readonly LoopCount: number = 14;
use `LOOP_COUNT`

2023-01-09 08:08 UTC, zhfnjust approved these changes
good work

2023-01-09 08:09 UTC, merged